/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * About.java
 *
 * Created on Feb 20, 2012, 9:50:45 PM
 */

package klinik.form;

import java.awt.event.ActionListener;

/**
 *
 * @author fendi
 */
public class About extends javax.swing.JPanel {

    /** Creates new form About */

    private static final long serialVersionUID = 1L;
    public About() {
        initComponents();
    }

    public void removeActionListener(ActionListener l) {
        buttonClose.removeActionListener(l);
    }

    public void addActionListener(ActionListener l) {
        buttonClose.addActionListener(l);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBacground1 = new klinik.form.template.PanelBacground();
        buttonBig1 = new klinik.form.template.ButtonBig();
        buttonClose = new klinik.form.template.Button();
        label1 = new klinik.form.template.Label();
        label2 = new klinik.form.template.Label();
        label3 = new klinik.form.template.Label();
        label4 = new klinik.form.template.Label();
        label5 = new klinik.form.template.Label();
        label6 = new klinik.form.template.Label();

        setLayout(new java.awt.BorderLayout());

        buttonBig1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/klinik/form/ico/icon_big_petclinic.png"))); // NOI18N
        buttonBig1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBig1ActionPerformed(evt);
            }
        });

        buttonClose.setText("close");

        label1.setText("Nama");

        label2.setText("Jurusan");

        label3.setText("Lia Paramita");

        label4.setText("Teknik Informatika");

        label5.setText("Program");

        label6.setText("Sistem Informasi Klinik v1.0");

        javax.swing.GroupLayout panelBacground1Layout = new javax.swing.GroupLayout(panelBacground1);
        panelBacground1.setLayout(panelBacground1Layout);
        panelBacground1Layout.setHorizontalGroup(
            panelBacground1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBacground1Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(panelBacground1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBacground1Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(buttonBig1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(45, 45, 45))
                    .addGroup(panelBacground1Layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(buttonClose, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                        .addGap(93, 93, 93)))
                .addGap(71, 71, 71))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBacground1Layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addGroup(panelBacground1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(label5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
                    .addComponent(label2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
                    .addComponent(label1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(panelBacground1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(label6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(label4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46))
        );
        panelBacground1Layout.setVerticalGroup(
            panelBacground1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBacground1Layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(buttonBig1, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelBacground1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelBacground1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelBacground1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(buttonClose, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(108, 108, 108))
        );

        add(panelBacground1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonBig1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBig1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonBig1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private klinik.form.template.ButtonBig buttonBig1;
    private klinik.form.template.Button buttonClose;
    private klinik.form.template.Label label1;
    private klinik.form.template.Label label2;
    private klinik.form.template.Label label3;
    private klinik.form.template.Label label4;
    private klinik.form.template.Label label5;
    private klinik.form.template.Label label6;
    private klinik.form.template.PanelBacground panelBacground1;
    // End of variables declaration//GEN-END:variables

}
