/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FormUtama.java
 *
 * Created on Feb 20, 2012, 10:26:03 PM
 */

package klinik.form;

import usu.widget.Form;

/**
 *
 * @author fendi
 */
public class FormUtama extends Form {

    /** Creates new form FormUtama */
    private static final long serialVersionUID = 1L;
    public FormUtama() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBacground1 = new klinik.form.template.PanelBacground();
        panelBacground3 = new klinik.form.template.PanelBacground();
        label1 = new klinik.form.template.Label();
        label2 = new klinik.form.template.Label();
        jPanel1 = new javax.swing.JPanel();
        panelBacground2 = new klinik.form.template.PanelBacground();
        button1 = new klinik.form.template.Button();
        button2 = new klinik.form.template.Button();
        button3 = new klinik.form.template.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        label1.setText("Copyright by Lia");

        javax.swing.GroupLayout panelBacground3Layout = new javax.swing.GroupLayout(panelBacground3);
        panelBacground3.setLayout(panelBacground3Layout);
        panelBacground3Layout.setHorizontalGroup(
            panelBacground3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBacground3Layout.createSequentialGroup()
                .addContainerGap(789, Short.MAX_VALUE)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelBacground3Layout.setVerticalGroup(
            panelBacground3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBacground3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        label2.setText("Klinik Beranda");
        label2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout panelBacground1Layout = new javax.swing.GroupLayout(panelBacground1);
        panelBacground1.setLayout(panelBacground1Layout);
        panelBacground1Layout.setHorizontalGroup(
            panelBacground1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBacground3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelBacground1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(673, 673, 673))
            .addGroup(panelBacground1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 894, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelBacground1Layout.setVerticalGroup(
            panelBacground1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBacground1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 445, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelBacground3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(panelBacground1, java.awt.BorderLayout.CENTER);

        button1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/klinik/form/ico/About.png"))); // NOI18N
        button1.setText("tentang");

        button2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/klinik/form/ico/exit.png"))); // NOI18N
        button2.setText("logout");

        button3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/klinik/form/ico/home-ico.png"))); // NOI18N
        button3.setText("beranda");

        javax.swing.GroupLayout panelBacground2Layout = new javax.swing.GroupLayout(panelBacground2);
        panelBacground2.setLayout(panelBacground2Layout);
        panelBacground2Layout.setHorizontalGroup(
            panelBacground2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBacground2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(button2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(button3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 575, Short.MAX_VALUE)
                .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelBacground2Layout.setVerticalGroup(
            panelBacground2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBacground2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelBacground2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        getContentPane().add(panelBacground2, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private klinik.form.template.Button button1;
    private klinik.form.template.Button button2;
    private klinik.form.template.Button button3;
    private javax.swing.JPanel jPanel1;
    private klinik.form.template.Label label1;
    private klinik.form.template.Label label2;
    private klinik.form.template.PanelBacground panelBacground1;
    private klinik.form.template.PanelBacground panelBacground2;
    private klinik.form.template.PanelBacground panelBacground3;
    // End of variables declaration//GEN-END:variables

}
