/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FormLogin.java
 *
 * Created on Feb 20, 2012, 8:35:09 PM
 */

package klinik.form;

import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import usu.widget.Form;

/**
 *
 * @author fendi
 */
public class FormLogin extends Form {

    /** Creates new form FormLogin */
    private static final long serialVersionUID = 1L;
    private FormUtama fu;
    public FormLogin(){
        fu = new FormUtama();
        initComponents();
        setMinimumSize(new Dimension(925, 700));
//        this.setResizable(false);
        setLocationRelativeTo(null);
    }

    public void initActions(){
        //MenuUtama
//        menuUtama.addActionListenerFilm(new AksiButton_MenuUtama_Film());
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        glasspane = new usu.widget.GlassPane();
        about1 = new klinik.form.About();
        panelBacground1 = new klinik.form.template.PanelBacground();
        button1 = new klinik.form.template.Button();
        buttonBig1 = new klinik.form.template.ButtonBig();
        label1 = new klinik.form.template.Label();
        label2 = new klinik.form.template.Label();
        textBox1 = new klinik.form.template.TextBox();
        passwordBox1 = new klinik.form.template.PasswordBox();
        button2 = new klinik.form.template.Button();
        label3 = new klinik.form.template.Label();

        setGlassPane(glasspane);
        getGlassPane().setVisible(true);
        glasspane.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 6, 6));

        about1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                about1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        button1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/klinik/form/ico/About.png"))); // NOI18N
        button1.setText("tentang");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });

        buttonBig1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/klinik/form/ico/icon_big_petclinic.png"))); // NOI18N

        label1.setText("Username  :");
        label1.setFont(new java.awt.Font("Tahoma", 1, 14));

        label2.setText("Password  :");
        label2.setFont(new java.awt.Font("Tahoma", 1, 14));

        button2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/klinik/form/ico/login-icon.png"))); // NOI18N
        button2.setText("masuk");
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2ActionPerformed(evt);
            }
        });

        label3.setText("Klinik Login");
        label3.setFont(new java.awt.Font("Rockwell", 1, 36));

        javax.swing.GroupLayout panelBacground1Layout = new javax.swing.GroupLayout(panelBacground1);
        panelBacground1.setLayout(panelBacground1Layout);
        panelBacground1Layout.setHorizontalGroup(
            panelBacground1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBacground1Layout.createSequentialGroup()
                .addContainerGap(749, Short.MAX_VALUE)
                .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(panelBacground1Layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, 536, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(86, 86, 86))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBacground1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonBig1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addGroup(panelBacground1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelBacground1Layout.createSequentialGroup()
                        .addGroup(panelBacground1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelBacground1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(passwordBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(button2, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(96, 96, 96))
        );
        panelBacground1Layout.setVerticalGroup(
            panelBacground1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBacground1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(panelBacground1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBacground1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(buttonBig1, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelBacground1Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(panelBacground1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panelBacground1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(passwordBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(button2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(106, 106, 106))
        );

        getContentPane().add(panelBacground1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        // TODO add your handling code here:
        glasspane.showComponent(about1);
    }//GEN-LAST:event_button1ActionPerformed

    private void about1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_about1ActionPerformed
        // TODO add your handling code here:
        glasspane.hideComponent();
    }//GEN-LAST:event_about1ActionPerformed

    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed
        // TODO add your handling code here:
        fu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_button2ActionPerformed

    /**
    * @param args the command line arguments
    */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private klinik.form.About about1;
    private klinik.form.template.Button button1;
    private klinik.form.template.Button button2;
    private klinik.form.template.ButtonBig buttonBig1;
    usu.widget.GlassPane glasspane;
    private klinik.form.template.Label label1;
    private klinik.form.template.Label label2;
    private klinik.form.template.Label label3;
    private klinik.form.template.PanelBacground panelBacground1;
    private klinik.form.template.PasswordBox passwordBox1;
    private klinik.form.template.TextBox textBox1;
    // End of variables declaration//GEN-END:variables

    
}
