/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MenuPeriksa.java
 *
 * Created on Feb 21, 2012, 2:05:52 AM
 */

package klinik.form;

/**
 *
 * @author fendi
 */
public class MenuPeriksa extends javax.swing.JPanel {

    /** Creates new form MenuPeriksa */
    public MenuPeriksa() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label1 = new klinik.form.template.Label();
        textBox1 = new klinik.form.template.TextBox();
        button1 = new klinik.form.template.Button();
        scrollPane1 = new usu.rental.film.widget.ScrollPane();
        scrollPane2 = new usu.rental.film.widget.ScrollPane();
        jPanel1 = new javax.swing.JPanel();
        label2 = new klinik.form.template.Label();
        textBox2 = new klinik.form.template.TextBox();
        label3 = new klinik.form.template.Label();
        textBox3 = new klinik.form.template.TextBox();
        label4 = new klinik.form.template.Label();
        label5 = new klinik.form.template.Label();
        formatterBox1 = new klinik.form.template.FormatterBox();
        label6 = new klinik.form.template.Label();
        textBox4 = new klinik.form.template.TextBox();
        label7 = new klinik.form.template.Label();
        label8 = new klinik.form.template.Label();
        label9 = new klinik.form.template.Label();
        button3 = new klinik.form.template.Button();
        button4 = new klinik.form.template.Button();
        button2 = new klinik.form.template.Button();
        scrollPane3 = new usu.rental.film.widget.ScrollPane();
        textArea1 = new usu.rental.film.widget.TextArea();
        scrollPane5 = new usu.rental.film.widget.ScrollPane();
        textArea2 = new usu.rental.film.widget.TextArea();
        scrollPane6 = new usu.rental.film.widget.ScrollPane();
        textArea4 = new usu.rental.film.widget.TextArea();
        scrollPane7 = new usu.rental.film.widget.ScrollPane();
        textArea3 = new usu.rental.film.widget.TextArea();

        setOpaque(false);

        label1.setText("Pencarian"); // NOI18N

        textBox1.setText("textBox1"); // NOI18N

        button1.setText("cari"); // NOI18N

        jPanel1.setOpaque(false);

        label2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        label2.setText("No. Pasien :"); // NOI18N

        textBox2.setText("textBox2"); // NOI18N

        label3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        label3.setText("Nama Pasien :"); // NOI18N

        textBox3.setText("textBox3"); // NOI18N

        label4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        label4.setText("Tanggal Berobat :"); // NOI18N

        label5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        label5.setText("Keluhan :"); // NOI18N

        formatterBox1.setText("formatterBox1"); // NOI18N

        label6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        label6.setText("Dokter :"); // NOI18N

        textBox4.setText("textBox4"); // NOI18N

        label7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        label7.setText("Diagnosa :"); // NOI18N

        label8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        label8.setText("Pengobatan :"); // NOI18N

        label9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        label9.setText("Alergi Obat :"); // NOI18N

        button3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/klinik/form/ico/add-icon.png"))); // NOI18N
        button3.setText("tambah"); // NOI18N

        button4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/klinik/form/ico/301px-Orange_Icon_Edit.svg.png"))); // NOI18N
        button4.setText("edit"); // NOI18N

        button2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/klinik/form/ico/remove_256.png"))); // NOI18N
        button2.setText("hapus"); // NOI18N

        textArea1.setColumns(20);
        textArea1.setRows(5);
        textArea1.setSelectionColor(new java.awt.Color(255, 0, 51));
        scrollPane3.setViewportView(textArea1);

        textArea2.setColumns(20);
        textArea2.setRows(5);
        textArea2.setSelectionColor(new java.awt.Color(255, 0, 51));
        scrollPane5.setViewportView(textArea2);

        textArea4.setColumns(20);
        textArea4.setRows(5);
        textArea4.setSelectionColor(new java.awt.Color(255, 0, 51));
        scrollPane6.setViewportView(textArea4);

        textArea3.setColumns(20);
        textArea3.setRows(5);
        textArea3.setSelectionColor(new java.awt.Color(255, 0, 51));
        scrollPane7.setViewportView(textArea3);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(button3, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(button4, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(button2, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(label6, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(textBox4, javax.swing.GroupLayout.DEFAULT_SIZE, 490, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textBox2, javax.swing.GroupLayout.DEFAULT_SIZE, 490, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(textBox3, javax.swing.GroupLayout.DEFAULT_SIZE, 490, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(formatterBox1, javax.swing.GroupLayout.DEFAULT_SIZE, 490, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(scrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 490, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label7, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label9, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label8, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(scrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 490, Short.MAX_VALUE)
                            .addComponent(scrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 490, Short.MAX_VALUE)
                            .addComponent(scrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 490, Short.MAX_VALUE))))
                .addGap(42, 42, 42))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(formatterBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(scrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label6, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label7, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(scrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label8, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(scrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label9, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(scrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(190, Short.MAX_VALUE))
        );

        scrollPane2.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 679, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(scrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 679, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private klinik.form.template.Button button1;
    private klinik.form.template.Button button2;
    private klinik.form.template.Button button3;
    private klinik.form.template.Button button4;
    private klinik.form.template.FormatterBox formatterBox1;
    private javax.swing.JPanel jPanel1;
    private klinik.form.template.Label label1;
    private klinik.form.template.Label label2;
    private klinik.form.template.Label label3;
    private klinik.form.template.Label label4;
    private klinik.form.template.Label label5;
    private klinik.form.template.Label label6;
    private klinik.form.template.Label label7;
    private klinik.form.template.Label label8;
    private klinik.form.template.Label label9;
    private usu.rental.film.widget.ScrollPane scrollPane1;
    private usu.rental.film.widget.ScrollPane scrollPane2;
    private usu.rental.film.widget.ScrollPane scrollPane3;
    private usu.rental.film.widget.ScrollPane scrollPane5;
    private usu.rental.film.widget.ScrollPane scrollPane6;
    private usu.rental.film.widget.ScrollPane scrollPane7;
    private usu.rental.film.widget.TextArea textArea1;
    private usu.rental.film.widget.TextArea textArea2;
    private usu.rental.film.widget.TextArea textArea3;
    private usu.rental.film.widget.TextArea textArea4;
    private klinik.form.template.TextBox textBox1;
    private klinik.form.template.TextBox textBox2;
    private klinik.form.template.TextBox textBox3;
    private klinik.form.template.TextBox textBox4;
    // End of variables declaration//GEN-END:variables

}
